speller:
	clang -ggdb3 -O0 -Qunused-arguments -std=c11 -Wall -Werror -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wshadow -c -o speller.o speller.c
	clang -ggdb3 -O0 -Qunused-arguments -std=c11 -Wall -Werror -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wshadow -c -o dictionary.o dictionary.c
	clang -ggdb3 -O0 -Qunused-arguments -std=c11 -Wall -Werror -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wshadow -o speller speller.o dictionary.o -lm

#speller_explanation.pdf: speller_explanation.md
	#pandoc speller_explanation.md -f markdown -t pdf -o speller_explanation.pdf --pdf-engine pdflatex

#lecture_notes.pdf: lecture_notes.md
	#pandoc lecture_notes.md -f markdown -t pdf -o lecture_note.pdf --pdf-engine pdflatex
